FROM pustudy/hellorun:1

RUN mkdir -p /home/zoul15/testdir/
WORKDIR /home/zoul15/testdir/
COPY testdir/ /home/zoul15/testdir/

RUN mkdir -p /home/zoul15/testdirdata/
WORKDIR /home/zoul15/testdirdata/
COPY testdirdata/ /home/zoul15/testdirdata/

RUN mkdir -p /home/zoul15/testdirdata/testdata/